name: Run autoconf make

inputs:
  dir:
    description: |
      The directory containing the Makefile.
    default: .

needs:
  packages:
    - make

pipeline:
  - runs: |
      make -C "${{inputs.dir}}" -j$(nproc)
