name: Run autoconf make

inputs:
  dir:
    description: |
      The directory containing the Makefile.
    default: .

needs:
  packages:
    - make

pipeline:
  - runs: |
      cd ${{inputs.dir}}
      make -j$(nproc)
