name: Run autoconf make install

inputs:
  dir:
    description: |
      The directory containing the Makefile.
    default: .

needs:
  packages:
    - make

pipeline:
  - runs: |
      make -C "${{inputs.dir}}" install DESTDIR="${{targets.destdir}}" V=1
