name: Split manpages

pipeline:
  - runs: |
      if [ -d "${{targets.destdir}}/usr/share/man" ]; then
        mkdir -p "${{targets.subpkgdir}}/usr/share"
        mv "${{targets.destdir}}/usr/share/man" "${{targets.subpkgdir}}/usr/share"
      fi
