name: Fetch and extract external object into workspace

needs:
  packages:
    - wget

inputs:
  strip-components:
    description: |
      The number of path components to strip while extracting.
    default: 1

  extract:
    description: |
      Whether to extract the downloaded artifact as a source tarball.
    default: true

  expected-sha256:
    description: |
      The expected SHA256 of the downloaded artifact.
    default: "NOTSET"

  expected-sha512:
    description: |
      The expected SHA512 of the downloaded artifact.
    default: "NOTSET"

  uri:
    description: |
      The URI to fetch as an artifact.
    required: true

pipeline:
  - runs: |
      wget ${{inputs.uri}}
      bn=$(basename ${{inputs.uri}})
      if [ "${{inputs.expected-sha256}}" != "NOTSET" ]; then
        printf "%s  %s\n" '${{inputs.expected-sha256}}' $bn | sha256sum -c
      fi
      if [ "${{inputs.expected-sha512}}" != "NOTSET" ]; then
        printf "%s  %s\n" '${{inputs.expected-sha512}}' $bn | sha512sum -c
      fi
      if [ "${{inputs.expected-sha512}}" == "NOTSET" && "${{inputs.expected-sha256}}" == "NOTSET" ]; then
        printf "One of expected-sha256 or expected-sha512 is required"
        exit 1
      fi

      if [ "${{inputs.extract}}" = "true" ]; then
        bn=$(basename ${{inputs.uri}})
        tar -x '--strip-components=${{inputs.strip-components}}' -f $bn
      fi
