name: Apply patches

inputs:
  strip-components:
    description: |
      The number of path components to strip while extracting.
    default: 1

  patches:
    description: |
      A list of patches to apply, as a whitespace delimited string.
    required: true

pipeline:
  - runs: |
      for i in ${{inputs.patches}}; do
        patch -p${{inputs.strip-components}} < $i
      done
