package:
  name: hello
  version: 0
  epoch: 0
  description: "a hello world program"
  copyright:
    - attestation: This program is in the public domain.
      license: CC-PDDC
  resources:
    cpu: .5
    memory: 128Mi

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

pipeline:
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
