package:
  name: test-git-checkout
  version: 6.14
  epoch: 0
  description: This package mainly just tests git-checkout pipeline
environment:
  contents:
    packages:
      - busybox
      - git
vars:
  workd: /tmp/test-git-checkout-workd
  giturl: "file:///tmp/test-git-checkout-workd/repos/my-repo"
pipeline:
  - name: "Create the bogus package content"
    runs: |
      echo "package does not do anything" > "${{targets.contextdir}}/README"
  - name: "Create a git repo"
    runs: |
      rm -Rf ${{vars.workd}}
      mkdir -p ${{vars.workd}}/repos
      repo=${{vars.workd}}/repos/my-repo

      ./create-git-repo "$repo"
      touch "$repo/git-daemon-export-ok"
  - runs: |
      vr() { echo "$@" 1>&2; "$@"; }
      vr git clone "${{vars.giturl}}" my3.git
  - name: "standard tag on branch"
    uses: git-checkout
    working-directory: standard
    with:
      repository: ${{vars.giturl}}
      tag: 2.0
      expected-commit: 3dfc3dd573b814be48c07f7f8ae3c19a23b69865
  - name: "check standard tag on branch"
    working-directory: standard
    runs: |
      hash=$(git rev-parse --verify HEAD)
      [ "$hash" = 3dfc3dd573b814be48c07f7f8ae3c19a23b69865 ]
