package:
  name: hello-go
  version: v0.0.1
  epoch: 0
  description: "simple hello go project"
  target-architecture:
    - all

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/puerco/hello/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha512: 8b6a997ef52711cfe29ede1510cd4b2181e2397eb89e0114feb6b6829dc01e400154e8021fe8be58ae8cad1c97152721a61c3ab88f68009d1bb7b2263aac6a18
  - uses: go/build
    with:
      packages: main.go
      output: hello
      
      # Example to pass tags to compiler:
      # tags: hello,bye

      # Example to pass ldflags to compiler 
      # ldflags: -buildid= sigs.k8s.io/release-utils/version.gitCommit=406d901bef12a92957f47f8a539d6bc6e6e13ca5