name: Install project with meson

inputs:
  output-dir:
    description: |
      The output directory for the Meson build.
    default: output

pipeline:
  - runs: |
      DESTDIR="${{targets.destdir}}" meson install -C ${{inputs.output-dir}}
