name: ci

on:
  pull_request:
  push:

env:
  GO_VERSION: 1.18

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0

      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: build
        run: |
          make melange
          ./melange version

      - uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1 # v2.8.1
        with:
          version: v1.5.0
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/melange-build_linux_amd64/melange version
