name: ci

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.20'
          check-latest: true

      - name: build
        run: |
          make melange
          ./melange version

      - uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          version: latest
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/melange-build_linux_amd64_v1/melange version
