name: e2e melange bootstrap + build

on:
  push:
  pull_request:

jobs:
  build:
    name: Release melange image
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: |
        --cap-add NET_ADMIN --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor:unconfined

    steps:
    - uses: actions/checkout@main
    # We have to do this because GitHub Actions does not make it
    # easy to disable seccomp, despite giving root access to the underlying
    # VM...
    - name: Run e2e script in Docker
      run: |
        cd ${GITHUB_WORKSPACE}
        ./hack/e2e-bootstrap.sh
