name: e2e melange bootstrap + build

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.17.x

jobs:
  build:
    name: Release melange image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    # We have to do this because GitHub Actions does not make it
    # easy to disable seccomp, despite giving root access to the underlying
    # VM...
    - name: Run e2e script in Docker
      run: |
        docker run --cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/fuse \
          --security-opt apparmor:unconfined --security-opt seccomp=unconfined \
          --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_REF \
          -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW \
          -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE \
          -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE \
          -e RUNNER_TEMP -e RUNNER_WORKSPACE -v /var/run/docker.sock:/var/run/docker.sock \
          -v '/home/runner/work/_temp/_github_home:/github/home' \
          -v '/home/runner/work/_temp/_github_workflow:/github/workflow' \
          -v '/dev:/dev' \
          -v ${GITHUB_WORKSPACE}:/github/workspace -i alpine:latest \
          /github/workspace/e2e.sh
