name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.0.0
      with:
        go-version: 1.18
        check-latest: true
    - name: Checkout code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Test
      run: make test
