name: Create Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  GO_VERSION: 1.18

jobs:
  cli:
    name: Release the CLI
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3.0.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
    - uses: sigstore/cosign-installer@09a077b27eb1310dcfb21981bee195b30ce09de0 # v2.4.1
    - uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # v2.8.1
      with:
        version: latest
        install-only: true
    - name: Release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ko-build:
    name: Release melange image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      COSIGN_EXPERIMENTAL: "true"

    steps:
    - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3.0.0
      with:
        go-version: ${{ env.GO_VERSION }}
        check-latest: true

    - uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

    - uses: sigstore/cosign-installer@09a077b27eb1310dcfb21981bee195b30ce09de0 # v2.4.1

    - uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v1.13.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

    - name: Publish/Sign melange image
      run: |
        make sign-image
